name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version-file: .nvmrc
      - name: Node Modules Cache
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Install
        if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Check Formatting
        run: npm run format:check
