name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version-file: .nvmrc
      - name: Node Modules Cache
        id: node_modules_cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Install
        if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Check Formatting
        run: npm run format:check
