on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-core:
    name: Release @gemini-ui-astro/core
    uses: ./.github/workflows/workflow-partial-release-npm.yml
    with:
      package_path: packages/core
    secrets: inherit
  release-styles:
    name: Release @gemini-ui-astro/styles
    uses: ./.github/workflows/workflow-partial-release-npm.yml
    with:
      package_path: packages/styles
    secrets: inherit
  release-components:
    name: Release @gemini-ui-astro/components
    needs: [release-core]
    uses: ./.github/workflows/workflow-partial-release-npm.yml
    with:
      package_path: packages/styles
    secrets: inherit
  release-components-blog:
    name: Release @gemini-ui-astro/components-blog
    needs: [release-components]
    uses: ./.github/workflows/workflow-partial-release-npm.yml
    with:
      package_path: packages/components-blog
    secrets: inherit
